# fly.toml app configuration file generated for celio-patient-firefly-4552 on 2025-07-07T18:10:41-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'celio-patient-firefly-4552'
primary_region = 'iad'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  DJANGO_DEBUG = 'False'
  DJANGO_SETTINGS_MODULE = 'celio.settings'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['web']


  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  web = "gunicorn celio.wsgi:application --bind 0.0.0.0:$PORT"

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
