# Generated by Django 5.1.5 on 2025-03-27 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('language', models.CharField(max_length=100)),
                ('language_code', models.CharField(max_length=2)),
                ('celiac_awareness', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=3)),
                ('summary', models.TextField(help_text='General information about celiac awareness in this country')),
                ('dining_tips', models.TextField(help_text='Tips for dining safely in this country')),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DishesToAvoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('local_name', models.CharField(blank=True, help_text='Name in local language', max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.TextField(help_text='Common ingredients that contain gluten')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes_to_avoid', to='travel.country')),
            ],
            options={
                'verbose_name_plural': 'Dishes to Avoid',
            },
        ),
        migrations.CreateModel(
            name='RestaurantPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.TextField()),
                ('translated_text', models.TextField(help_text='Translation in local language')),
                ('pronunciation', models.TextField(blank=True, help_text='Pronunciation guide if applicable')),
                ('category', models.CharField(choices=[('general', 'General'), ('ordering', 'Ordering'), ('ingredients', 'Ingredients'), ('emergency', 'Emergency')], default='general', max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_phrases', to='travel.country')),
            ],
        ),
    ]
