# Generated by Django 5.1.8 on 2025-07-09 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_alter_country_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attraction',
        ),
    ]
