# Generated by Django 5.1.8 on 2025-07-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_delete_attraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('local_name', models.CharField(blank=True, help_text='Name in local language', max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('monument', 'Monument'), ('museum', 'Museum'), ('landmark', 'Landmark'), ('park', 'Park/Garden'), ('religious', 'Religious Site'), ('cultural', 'Cultural Site')], default='landmark', max_length=20)),
                ('gluten_free_info', models.TextField(blank=True, help_text='Information about gluten-free options at or near this attraction')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='travel.country')),
            ],
            options={
                'verbose_name_plural': 'Attractions',
                'ordering': ['name'],
            },
        ),
    ]
