# Generated by Django 4.2.22 on 2025-07-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_restaurantphrase_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
