# Generated by Django 5.1.5 on 2025-02-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycard',
            name='custom_message',
        ),
        migrations.AddField(
            model_name='emergencycard',
            name='translations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
