# Generated by Django 5.1.5 on 2025-03-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_cards', '0003_alter_emergencycard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycard',
            name='language',
        ),
        migrations.AddField(
            model_name='emergencycard',
            name='preferred_language',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('ZH', 'Chinese'), ('JA', 'Japanese'), ('PT', 'Portuguese')], default='EN', help_text='The primary language for your card interface. You can still add translations in other languages', max_length=2, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='emergencycard',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal')], default='classic', help_text='Select the theme for your card', max_length=20, verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='condition',
            field=models.CharField(choices=[('CEL', 'Celiac Disease'), ('SEN', 'Gluten Sensitive'), ('ALL', 'Wheat/Gluten Allergy')], help_text='Select the option that best describes your dietary restriction', max_length=3, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='emergency_contact_name',
            field=models.CharField(help_text='Person to contact in case of an emergency', max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='emergency_contact_phone',
            field=models.CharField(help_text='Include country code if traveling internationally (e.g., +1 555-123-4567).', max_length=20, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='emergency_contact_relationship',
            field=models.CharField(max_length=50, verbose_name='Emergency Contact Relationship'),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='translations',
            field=models.JSONField(default=dict, help_text='Stores the card content in multiple languages. At least English  (EN) is required.', verbose_name='Translations'),
        ),
    ]
