# Generated by Django 5.1.5 on 2025-03-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_cards', '0004_remove_emergencycard_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycard',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AddField(
            model_name='emergencycard',
            name='show_profile_pic',
            field=models.BooleanField(default=False, help_text='Enable to display your profile picture on the card', verbose_name='Show Profile Picture'),
        ),
    ]
