# Generated by Django 5.1.5 on 2025-03-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_cards', '0005_emergencycard_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycard',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='emergencycard',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencycard',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='emergencycard',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycard',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('zh', 'Chinese')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='emergencycard',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencycard',
            name='medications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencycard',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='emergencycard',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencycard',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='emergency_cards/'),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='condition',
            field=models.CharField(choices=[('CEL', 'Celiac Disease'), ('SEN', 'Gluten Sensitive'), ('ALL', 'Wheat/Gluten Allergy')], default='CEL', help_text='Select the option that best describes your dietary restriction', max_length=3, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Person to contact in case of an emergency', max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Include country code if traveling internationally (e.g., +1 555-123-4567).', max_length=20, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, verbose_name='Emergency Contact Relationship'),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('zh', 'Chinese')], default='en', help_text='The primary language for your card interface', max_length=2, verbose_name='Preferred Language'),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='show_profile_pic',
            field=models.BooleanField(default=True, verbose_name='Show Profile Picture'),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('medical', 'Medical'), ('dark', 'Dark')], default='classic', max_length=20),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='Stores the card content in multiple languages', verbose_name='Translations'),
        ),
    ]
