# Generated by Django 5.1.5 on 2025-03-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_cards', '0006_remove_emergencycard_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycard',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal'), ('medical', 'Medical'), ('dark', 'Dark'), ('nature', 'Nature'), ('vintage', 'Vintage'), ('playful', 'Playful'), ('pastel', 'Pastel'), ('luxury', 'Luxury'), ('neon', 'Neon'), ('geometric', 'Geometric'), ('cyberpunk', 'Cyberpunk')], default='classic', max_length=20),
        ),
    ]
