# Generated by Django 5.1.8 on 2025-06-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_cards', '0009_emergencycard_custom_note_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmergencyCard',
            new_name='Card',
        ),
        migrations.RenameField(
            model_name='Card',
            old_name='emergency_contact_name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='Card',
            old_name='emergency_contact_phone',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='Card',
            old_name='emergency_contact_relationship',
            new_name='contact_relationship',
        ),
    ]
