# Generated by Django 5.1.8 on 2025-06-25 22:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_cards', '0010_rename_model_and_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(choices=[('CEL', 'Celiac Disease'), ('SEN', 'Gluten Sensitive'), ('ALL', 'Wheat/Gluten Allergy')], default='CEL', help_text='Select the option that best describes your dietary restriction', max_length=3, verbose_name='Condition')),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Person to contact if needed', max_length=100, null=True, verbose_name='Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Include country code if traveling internationally (e.g., +1 555-123-4567).', max_length=20, null=True, verbose_name='Contact Phone')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Contact Relationship')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=10)),
                ('medical_conditions', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('custom_note', models.TextField(blank=True, help_text='Optional: Add a personal note to your card', verbose_name='Personal Note')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('zh', 'Chinese')], default='en', max_length=2)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('zh', 'Chinese')], default='en', help_text='The primary language for your card interface', max_length=2, verbose_name='Preferred Language')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='message_cards/')),
                ('show_profile_pic', models.BooleanField(default=True, verbose_name='Show Profile Picture')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('dark-purple', 'Dark Purple')], default='light', max_length=20)),
                ('translations', models.JSONField(blank=True, default=dict, help_text='Stores translations of the custom note', verbose_name='Translations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
