# Generated by Django 5.1.8 on 2025-06-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_cards', '0011_emergencycard_delete_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycard',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('zh', 'Chinese'), ('ko', 'Korean'), ('ar', 'Arabic'), ('ru', 'Russian'), ('hi', 'Hindi')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ja', 'Japanese'), ('zh', 'Chinese'), ('ko', 'Korean'), ('ar', 'Arabic'), ('ru', 'Russian'), ('hi', 'Hindi')], default='en', help_text='The primary language for your card interface', max_length=2, verbose_name='Preferred Language'),
        ),
        migrations.AlterField(
            model_name='emergencycard',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('purple', 'Dark'), ('dark', 'Purple')], default='light', max_length=20),
        ),
    ]
