# Generated by Django 5.1.8 on 2025-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_cards', '0012_alter_emergencycard_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycard',
            name='theme',
            field=models.CharField(choices=[('celio', 'Celio'), ('light', 'Light'), ('purple', 'Dark'), ('dark', 'Purple')], default='celio', max_length=20),
        ),
    ]
