# Generated by Django 5.1.8 on 2025-07-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_cards', '0013_alter_emergencycard_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycard',
            name='theme',
            field=models.CharField(choices=[('celio', 'Celio'), ('light', 'Light'), ('purple', 'Purple'), ('dark', 'Dark')], default='light', max_length=20),
        ),
    ]
