# Generated by Django 5.1.8 on 2025-07-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_cards', '0014_alter_emergencycard_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycard',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('purple', 'Dark'), ('dark', 'Purple')], default='light', max_length=20),
        ),
    ]
