# Generated by Django 4.2.22 on 2025-11-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_cards', '0015_alter_emergencycard_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycard',
            name='theme',
            field=models.CharField(choices=[('celio', 'Celio'), ('light', 'Light'), ('dark', 'Dark'), ('purple', 'Purple')], default='light', max_length=20),
        ),
    ]
